[package]
name = "bpadmm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bpadmm"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["extension-module"] }
num-traits = "*"
num-complex = "*"
dict_derive = "*"
numpy = "*"
rayon = "*"
crossbeam-channel = "*"
ndarray = { version = "0.15.0", features = ["blas"] }
blas-src = { version = "0.8", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
ndarray-linalg = {version = "0.16", features = ["openblas-system"]}
indicatif = "*"